---
# This role deploys the MariaDB processes and sets up settings.

- name: MariaDB | Add keys authenticity
  apt_key: url={{ url_apt_key }}0xcbcb082a1bb943db state=present

- name: MariaDB | Add source sources
  apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/debian wheezy main' update_cache=yes

- name: MariaDB | Install Packages
  apt: pkg={{ item }} state=installed
  with_items:
    - mariadb-server
    - python-mysqldb
    - mariadb-client
    - python-mysql.connector
  notify: Start mariadb

- name: MariaDB | Set root password
  mysql_user: login_user=root
              login_password={{ mariadb_current_password }}
              name=root
              host={{ item }}
              password={{ mariadb_root_password }}
              priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes
  notify: Restart mariadb

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: MariaDB | Remove the MySQL test database
  mysql_db: db=test state=absent
